article/urls.py
from django.urls import path,include
from . import views



app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list, name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path('',views.index_view,name='index_url'),
    path('search/',include('haystack.urls')),
    path('archives/<int:year>/<int:month>/',views.archive,name='archive'),
    path('columns/<int:pk>/',views.column,name='column')
]

mlog/urls.py
from django.urls import path,include
from . import views

app_name = 'mlog'

urlpatterns = [
    path('mlog-result/',views.mlog_result,name='mlog_result'),
    path('vlog-list/',views.vlog_list,name='vlog_list'),
    path('vlog/<int:pk>/',views.vlog_detail,name='vlog_detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from article.views import index_view
from django.views.generic.base import RedirectView
import notifications.urls


urlpatterns = [
    path('myblog/', admin.site.urls),
    path('',index_view,name='index_url'),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('accounts/',include('allauth.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('pciture/',include('picture.urls',namespace='picture')),
    path('mlog/',include('mlog.urls',namespace='mlog')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
]

templates/search/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load highlight %}
{% load article_extras %}
{% block content %}
<div class="container" style="padding-bottom: 60px">

                <a class="text-secondary disabled">当前搜索：{{query}}</a>
                {% for result in page.object_list %}

                    <div class="card mb-2  p-3 md-5 bg-white " style="display: flex">
                    <div class="row no-gutters align-items-center">
                        <div class="col">

                            <div class="card-body">

                                    <span class="blog-meta__post-by">{{ result.object.comments.count }}&nbsp;&nbsp;&nbsp;<i class="fas fa-comments " style="color: yellowgreen;"></i></span>
                                    <span class="blog-meta__separator">|</span>
                                    <span class="blog-meta__post-by">{{ result.object.total_views }}&nbsp;&nbsp;&nbsp;<i class="fas fa-eye " style="color: lightskyblue;"></i></span>
                                    <span class="blog-meta__separator">|</span>


                                <h4 class="blog-post__title">
                                <a class="text-secondary no-underline blog-post__title"   href="{% url 'article:article_detail' result.object.pk %}">{{result.object.title}}</a>
                            </h4>
                            <p class="f-15 blog-meta__post-by">
                                {% with result.object.body|safe as body %}
                                    <span>{% highlight body with query %}</span>
                                {% endwith %}
                            </p>
                        </div>
                        </div>
                    </div>
                </div>





                {% empty %}

                <h3>NONE</h3>
                {% endfor %}

</div>

{% endblock content %}