article/urls.py
from django.urls import path,include
from . import views



app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list, name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path('',views.index_view,name='index_url'),
    path('search/',include('haystack.urls')),
    path('archives/<int:year>/<int:month>/',views.archive,name='archive'),
    path('columns/<int:pk>/',views.column,name='column')
]

mlog/urls.py
from django.urls import path,include
from . import views

app_name = 'mlog'

urlpatterns = [
    path('mlog-result/',views.mlog_result,name='mlog_result'),
    path('vlog-list/',views.vlog_list,name='vlog_list'),
    path('vlog/<int:pk>/',views.vlog_detail,name='vlog_detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from article.views import index_view
from django.views.generic.base import RedirectView
import notifications.urls


urlpatterns = [
    path('myblog/', admin.site.urls),
    path('',index_view,name='index_url'),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('accounts/',include('allauth.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('pciture/',include('picture.urls',namespace='picture')),
    path('mlog/',include('mlog.urls',namespace='mlog')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/',views.CommentNoticeListView.as_view(),name='list'),
    path('update/',views.CommentNoticeUpdateView.as_view(),name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
    path('info/<int:id>/',views.profile_info,name='info'),
]

templates/back_to_top_func.html
<!-- 参考了 鹦鹉 的代码，在此致谢 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"><i class="fas fa-angle-up"></i></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 2.75rem;
        height: 2.75rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 25%;
        opacity: 0.2;
        background:#d1d9e0;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }



    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/footer.html
<div>
    <br><br><br>
</div>
<footer class="py-3  position-relative" style="background-color: #f0f0f4" >
    <div class="container">
        <p class="m-0 ">Powered by
            <a href="https://www.djangoproject.com/" target="_blank" class="text-dark">
                Django
            </a>&
            <a target="_blank" class="text-dark" href="https://getbootstrap.com/">Bootstrap</a>
        </p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-md navbar-light  " style="background-color: #f0f0f4">
 <div class="container">
    <!-- 导航栏商标 -->
    <a class="navbar-brand btn-default  border-0  header-humberger-icon" href="{% url 'index_url' %}">Lesphon</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
   </button>

    <div class="collapse navbar-collapse  justify-content-end" id="collapsibleNavbar" >

        <form class="nav-item navbar-form mr-2 py-md-2  " role="search" method="get" id="searchform" action="{% url 'article:haystack_search' %}">
            <div class="input-group rounded">
                <input type="text" name="q" class="form-control  bg-transparent border " placeholder="搜索" autocomplete="off" required=True>
                    <div class="input-group-btn">
                        <button class="btn btn-default hvr-icon-fade " type="submit"><i class="fa fa-search bg hvr-icon text-black-50"></i></button>
                    </div>
            </div><!-- /input-group -->
        </form>
        <ul class="nav navbar-nav  ">
           <!-- <li class="nav-item" >
                 <a class="nav-link " href="{% url 'article:article_list' %} ">文字</a>
            </li>
            -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'mlog:mlog_result' %}">日志</a>
            </li>
            <li class="nav-item">
                 <a class="nav-link" href="#">日志</a>
            </li>
            <li class="nav-item">
                 {% if user.is_superuser %}
                <div class="btn-group btn-default">
                    <a role="button" class="btn btn-default" href="{% url "userprofile:edit" user.id %}"><i class="fas fa-user text-secondary"></i></a>
                        <button class="btn btn-default dropdown-toggle dropdown-toggle-split" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                    <div class="dropdown-menu " aria-label="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'article:article_create' %}">发布</a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">退出</a>
                     </div>
                </div>
                 {% elif user.is_authenticated %}
                <div class="btn-group">
                    <a role="button" class="btn btn-light" href="{% url "userprofile:edit" user.id %}"><i class="fas fa-user text-secondary"></i></a>
                    <button class="btn btn-light dropdown-toggle dropdown-toggle-split" type="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
               <div class="dropdown-menu" aria-label="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'account_logout' %}">退出</a>
                </div>
                </div>
                {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt text-secondary"></i></a>
                    </li>
                {% endif %}
            </li>
        </ul>

    </div>
 </div>
 </nav>

templates/top_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div id="st-trigger-effects" class="column">
        <button class="fas fa-align-justify" id="open-button" style="border: none;background: transparent"></button>
    </div>
<div>
    <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="navbar-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   {% if unread_count %}
                       <svg viewBox="0 0 8 8" width="8px" height="8px">
                       <circle cx="4" cy="4" r="4" fill="#ff6bfb"></circle>
                       </svg>
                       {% endif %}
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'userprofile:edit' user.id%}">info</a>
                    <a class="dropdown-item" href="{% url 'notice:list' %}">message
                    {% if unread_count %}
                        <span class="badge badge-danger">
                        {{ unread_count }}
                        </span>
                        {% endif %}</a>
                    <a class="dropdown-item" href="{% url 'account_logout' %}">sign out</a>
                </div>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">sign in</a>
              </li>
          {% endif %}
    </ul>
</div>
  </div>
</nav>