article/urls.py
from django.urls import path,include
from . import views



app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list, name='article_list'),
    path('article-detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article-create/',views.article_create,name='article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name='article_update'),
    path('',views.index_view,name='index_url'),
    path('search/',include('haystack.urls')),
    path('archives/<int:year>/<int:month>/',views.archive,name='archive'),
    path('columns/<int:pk>/',views.column,name='column')
]

comment/urls.py
from  django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post-comment/<int:article_id>/',views.post_comment,name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>',views.post_comment,name='comment_reply'),
]

mlog/urls.py
from django.urls import path,include
from . import views

app_name = 'mlog'

urlpatterns = [
    path('mlog-result/',views.mlog_result,name='mlog_result'),
    path('vlog-list/',views.vlog_list,name='vlog_list'),
    path('vlog/<int:pk>/',views.vlog_detail,name='vlog_detail'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from article.views import index_view
from django.views.generic.base import RedirectView
import notifications.urls


urlpatterns = [
    path('myblog/', admin.site.urls),
    path('',index_view,name='index_url'),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('accounts/',include('allauth.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('pciture/',include('picture.urls',namespace='picture')),
    path('mlog/',include('mlog.urls',namespace='mlog')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
    path('info/<int:id>/',views.profile_info,name='info'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from  django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
import markdown
from django.utils.html import strip_tags
from .wan_storage_cos import QcloudStorage

# Create your models here.

class ArticleColumn(models.Model):
    title = models.CharField(max_length=100,blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class ArticlePost(models.Model):

    avatar = models.ImageField(verbose_name='文章图片',storage=QcloudStorage(),blank=True)
    tags = TaggableManager(blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    excerpt = models.CharField(max_length=200,blank=True)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    def save(self,*args,**kwargs):


        self.modified_time = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.excerpt = strip_tags(md.convert(self.body))[:54]

        super().save(*args,**kwargs)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id])

article/forms.py
from django import forms
from .models import ArticlePost


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body','tags')

article/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import ArticlePost,ArticleColumn
from django.http import HttpResponse
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required,permission_required
from django.core.paginator import Paginator
from comment.models import Comment
from comment.forms import CommentForm
import markdown
from django.views import generic
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
import re
from PIL import Image
from urllib.request import urlopen
from django.conf import settings

# Create your views here.

def column(request,pk):
    col = get_object_or_404(ArticleColumn,pk=pk)
    article_list = ArticlePost.objects.filter(column=col)
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    comments = Comment.objects.all()
    return render(request,'article/index.html',context={'articles':articles,'comments':comments})

def archive(request,year,month):
    articles= ArticlePost.objects.filter(created__year=year,
                                                  created__month=month
                                                  )

    return  render(request,'article/index.html',context={'articles':articles})


def index_view(request):
    article_list = ArticlePost.objects.all()
    paginator = Paginator(article_list, 5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    comments = Comment.objects.all()
    return render(request,'article/index.html',{'articles':articles,'comments':comments})  # 返回给index用于显示

def article_list(request):

    article_list = ArticlePost.objects.all()
    paginator = Paginator(article_list,5)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {'articles':articles}
    return render(request,'article/list.html',context)



def article_detail(request,id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    md=markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify),
    ])
    article.body = md.convert(article.body)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    article.toc = m.group(1) if m is not None else ''
    article.total_views += 1
    article.save(update_fields=['total_views'])
    comment_form = CommentForm()
    context = {'article':article,'comments':comments,'comment_form':comment_form,'toc':md.toc}

    return render(request,'article/detail.html',context)

@permission_required('article.can_add_article_post')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        if article_post_form.is_valid():
            new_article=article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("请重新填写")
    else:
        article_post_form = ArticlePostForm()
        context = {'article_post_form':article_post_form}
        return render(request,'article/create.html',context)

@permission_required('article.can_delete_article_post')
def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    article.delete()
    return redirect("article:article_list")

@permission_required('article.can_change_article_post')
def article_update(request, id):


    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = { 'article': article, 'article_post_form': article_post_form }
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} CREATE | MEMO {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}

                <!-- 文章标题 -->
                <div class="form-group">

                    <label for="title">文章标题</label>

                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                    <!-- 标签 -->
                      <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                    class="form-control col-3"
                    id="tags"
                    name="tags"
                    >
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
{% load article_extras %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    {{ article.title }} | MEMO
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<script>
    $(document).ready(function() {
        // 如果toc为空（只有最外层ul），隐藏整个TOC并返回
        if ($('.toc ul').children().length <= 0) {
            $('.toc').parent().css('display', 'none');
            return;
        }

        // 只显示1、2、3级目录列表
        $('.toc ul li ul li ul li ul').css('display', 'none');
        // 非默认的列表样式
        $('.toc').find('ul').addClass('u-list-inline');
        // 2、3级目录缩进
        $('.toc ul li ul li').addClass('g-ml-15');
        $('.toc ul li ul li ul li').addClass('g-ml-15');
        // 链接颜色，鼠标悬停颜色
        $('.toc').find('a').addClass('u-link-v5 g-color-aqua g-color-red--hover');
    });
</script>

<!-- 文章详情 -->
<div class="container " >
    <div class="row">
    <!-- 新增的目录 -->
    {% if article.toc %}
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
    {% endif %}
    <article class="{% if article.toc %}
                     blog-post col-9 shadow p-3 md-5 bg-white
                    {% else %}
                     blog-post col-12 shadow p-3 md-5 bg-white
                    {% endif %}"
                    >
    <h1 class="top-gap-0 blog-detail-title">{{ article.title }}</h1>
           <span class="blog-meta__date">{{ article.created }}&nbsp;&nbsp;</span>
            <span class="blog-meta__separator">|</span>
            <span class="blog-meta__comments"></i><!-- 修改为评论的计数 -->{{ article.comments.count }}&nbsp;&nbsp;comments</span>
            <span class="blog-meta__separator">|</span>
            <span class="blog-meta__post-by">by {{ article.author }}</span>
        <!-- 文章正文 -->
        <div class="col-12">
            <p class="blog-details-text">{{ article.body|safe }}</p>
        </div>

    </article>


    <section class="comment-area top-gap-big col" id="comment-area">
        <hr>
        {% if user.is_authenticated %}
        <div>
            <form action="{% url 'comment:post_comment' article.id %}" method='POST'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            评论:
                        </strong>
                    </label>
                    <div>
                        {{ comment_form.media }}
                        {{ comment_form.body }}
        </div>
                    <br>
                <button type="submit" class="btn btn-secondary">发布</button>
            </form>
        </div>
        <br>
        {% else %}
        <br>
        <h5 class="row justify-content-center glyphicon-text-size">
            登陆以回复:<a href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt"></i></a>
        </h5>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        {% endif %}
            <br>&nbsp;

    {% load mptt_tags %}
    <h4 >{{ comments.count }}条评论</h4>
    <div class="row">
        {% recursetree comments %}
            {% with comment=node %}
                <div class="{% if comment.reply_to %}
                            offset-1 col-11
                            {% else %}
                            col-12
                            {% endif %}"
                     id="comment_elem_{{ comment.id }}"
                     >

                        <hr>
                        <p>
                            <a style="color:gray" href="{% url "userprofile:info" comment.user.id %}">
                                {{ comment.user }}
                            </a>

                            {% if comment.reply_to %}
                                <i class="far fa-arrow-alt-circle-right"
                                   style="color:cornflowerblue;"
                                   ></i>
                                <a style="color:gray" href="{% url "userprofile:info" comment.reply_to.id %}">
                                    {{ comment.reply_to }}
                                </a>
                            {% endif %}
                        </p>
                        <div>{{ comment.body|safe }}</div>
                    <div>
                        <span style="color: gray">
                            {{ comment.created|date:"Y-m-d H:i" }}
                        </span>

                        {% if user.is_authenticated %}
                        <button type="button"
                                class="btn btn-light btn-sm text-muted"
                                onclick="load_modal({{ article.id }},{{ comment.id }})"
                                >
                            回复
                        </button>
                        {% else %}
                        <a class="btn btn-light btn-sm text-muted"
                           href="{% url 'userprofile:login' %}"
                           >
                            回复
                        </a>
                        {% endif %}
                    </div>

                    <div class="modal fade" id="comment_{{ comment.id }}" tabindex="-1" role="dialog" aria-labelledby="CommentModalCenter" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                            <div class="modal-content" style="height: 480px;">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalCenterTitle">回复{{ comment.user }}:</h5>
                                </div>
                                <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                            </div>

                        </div>
                    </div>

                {% if not comment.is_leaf_node %}

                    <div class="children">
                        {{ children }}
                    </div>
                {% endif %}
                </div>
    {% endwith %}
    {% endrecursetree %}
    </div>


{% block script %}
    <script>
    $(".django-ckeditor-widget").removeAttr('style');
    </script>

    <script>
 function load_modal(article_id, comment_id) {
    let modal_body = '#modal_body_' + comment_id;
    let modal_id = '#comment_' + comment_id;

    // 加载编辑器
    if ($(modal_body).children().length === 0) {
        let content = '<iframe src="/comment/post-comment/' +
            article_id +
            '/' +
            comment_id +
            '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
        $(modal_body).append(content);
    };

    $(modal_id).modal('show');
}


  function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };

    </script>
{% endblock script %}

    </section>
    </div>
</div>
{% endblock content %}

templates/article/index.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
{% load article_extras %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    MY MEMO
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-md-8">

            {% show_columns %}
            <!--普通文章显示-->
                {% for article in articles %}

                <div class="card mb-2  p-3 md-5 bg-white " style="display: flex">
                    <div class="row no-gutters align-items-center">
                        <div class="col">
                            {% if article.avatar %}
                            <img src="http://lesphon-1252495278.picsh.myqcloud.com/{{ article.avatar }}?imageMogr2/crop/x200/gravity/center" class="card-img-top " style="height:200px ">
                            {% endif %}
                            <div class="card-body">

                                    <span class="blog-meta__post-by">{{ article.total_views }}&nbsp;&nbsp;views</span>
                                    <span class="blog-meta__separator">|</span>
                                    <span class="blog-meta__comments"></i><!-- 修改为评论的计数 -->{{ article.comments.count }}&nbsp;&nbsp;comments</span>
                                    <span class="blog-meta__separator">|</span>
                                    <span>{{ article.created|timesince_zh }}</span>


                                <h4 class="blog-post__title">
                                <a class="text-secondary no-underline blog-post__title"   href="{% url 'article:article_detail' article.pk %}">{{ article.title }}</a>
                            </h4>
                            <p class="f-15 blog-meta__post-by">{{ article.excerpt|safe }}...</p>
                        </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="no-article">aaa</div>
                {% endfor %}

{% if articles.paginator.count > 5 %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  <!-- 如果不是第一页，则显示上翻按钮 -->
      {% if articles.has_previous %}
         <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="Previous">
             <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="?page={{ articles.previous_page_number }}">{{ articles.previous_page_number }}</a></li>
      {% endif %}
<!--当前页 -->
        <li class="page-item"><a class="page-link" href="#">{{ articles.number }}</a></li>
  <!-- 如果不是最末页，则显示下翻按钮 -->
    {% if articles.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ articles.next_page_number }}">{{ articles.next_page_number }}</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ articles.paginator.num_pages }}"><span aria-hidden="true">&raquo;</span></a>
        </li>
  {% endif %}
  </ul>
</nav>
{% endif %}
            </div>

            <div class="col-md-4">
                <div class="sidebar" id="sidebar" >
                    <div class="sidebar__inner">
                 {% show_recent_articles %}

                {% show_contactings %}

                {% show_archives %}
                    </div>
                </div>
            </div>

        </div>
    </div>

<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0);
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
<!-- 引入粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 60,
        bottomSpacing: 20,
    });
</script>
 {% include 'back_to_top_func.html' %}

{% endblock content %}

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
{% load article_extras %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文字 | MEMO
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <div class="row ">
        <div class="col-12">
            {% for article in articles %}
            {% if article.avatar %}
                            <img src="{{ avatars }}" class="card-img-top " style="">
{% endif %}
                {% if article.column %}
                    <button type="button" class="btn btn-sm mb-2 btn-dark">{{ article.column }}</button>
                {% endif %}

                    <span>
                     {% for tag in article.tags.all %}
                        <a href="{% url 'article:article_list' %}?tag={{ tag }}" class="badge badge-secondary">{{ tag }}</a>
                     {% endfor %}
                    </span>

                    <h4>
                        <b>
                            <a href="{% url 'article:article_detail' article.id %}" style="color: black;">
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>

                    <p style="color: gray;">
                        {{ article.body|slice:'100' }}...
                     </p>

                    <p>
                        <span>
                            <i class="fas fa-eye" style="color: lightskyblue;"></i>
                            {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                        </span>
                        <span>
                            <i class="fas fa-comments" style="color: yellowgreen;"></i>
                             <!-- 修改为评论的计数 -->
                            {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                        </span>
                        <span>
                            <i class="fas fa-clock" style="color: pink;"></i>
                            {{ article.created|timesince_zh }}
                        </span>
                    </p>
                    <hr>

            {% endfor %}
        </div>
    </div>
</div>
 <div class="pagination row ">
    <div class="m-auto ">
        <span class="step-links  center-block">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1" class="btn btn-primary">
                    &laquo; 1
                </a>
                <a href="?page={{ articles.previous_page_number }}"
                   class="btn btn-secondary"
                >
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

            <!-- 当前页面 -->
            <span class="current btn btn-secondary">
                {{ articles.number }}
            </span>

            <!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}"
                   class="btn btn-primary"
                >
                    {{ articles.next_page_number }}
                </a>

                <a href="?page={{ articles.paginator.num_pages }}"
                   class="btn btn-secondary"
                >
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock content %}

templates/article/list_2.html
<div class="list-group">
  <a class="list-group-item disabled">文章标题</a>
{% for article in article_list %}
  <a href="{% url 'blog:article_url' article.id %}" class="list-group-item">{{article.title}}</a>
{% empty %}
<h3>暂时没有文章!</h3>
{% endfor %}
</div>

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} UPDATE | MEMO {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>

                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}